const STREAM_BASE =
  import.meta.env.VITE_STREAM_BASE_URL || "http://localhost:9090";

const catalogItems = [
  {
    id: "featured-speedcast",
    title: "Speedcast Demo",
    subtitle: "Conteúdo em destaque",
    description:
      "Teste o player web com um vídeo real do servidor on-demand e uma experiência visual mais próxima de uma plataforma de streaming.",
    duration: "08 min",
    category: "Destaques",
    badge: "EM ALTA",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#1d4ed8",
    teacher: "Equipe EduCast",
    lessons: 4,
    progress: 0.32,
    year: "2026",
    rating: "Livre",
  },
  {
    id: "vod-1",
    title: "Boas-vindas ao EduCast",
    subtitle: "Introdução",
    description:
      "Primeiro contato com a plataforma, seus recursos e o fluxo de navegação.",
    duration: "08 min",
    category: "Continue assistindo",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#0f766e",
    teacher: "Prof. Mariana",
    lessons: 6,
    progress: 0.58,
    year: "2026",
    rating: "Livre",
  },
  {
    id: "vod-2",
    title: "Recursos da plataforma",
    subtitle: "Funcionalidades",
    description:
      "Visão geral sobre catálogo, progresso, busca e experiência em múltiplas telas.",
    duration: "08 min",
    category: "Continue assistindo",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#6d28d9",
    teacher: "Prof. Lucas",
    lessons: 5,
    progress: 0.41,
    year: "2026",
    rating: "Livre",
  },
  {
    id: "vod-3",
    title: "Aprendizado contínuo",
    subtitle: "Trilha recomendada",
    description:
      "Estruture jornadas de estudo com playlists e evolução do aluno.",
    duration: "08 min",
    category: "Recomendados",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#b45309",
    teacher: "Prof. Amanda",
    lessons: 8,
    progress: 0,
    year: "2026",
    rating: "10+",
  },
  {
    id: "vod-4",
    title: "Inclusão digital na prática",
    subtitle: "Projetos reais",
    description:
      "Como desenhar soluções mais acessíveis para contextos escolares distintos.",
    duration: "12 min",
    category: "Novidades",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#be123c",
    teacher: "Prof. Ricardo",
    lessons: 3,
    progress: 0,
    year: "2026",
    rating: "Livre",
  },
  {
    id: "vod-5",
    title: "Planejamento de aula híbrida",
    subtitle: "Estratégia",
    description:
      "Métodos para combinar vídeo, apoio visual e atividade em sala.",
    duration: "15 min",
    category: "Novidades",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#7c3aed",
    teacher: "Prof. Helena",
    lessons: 7,
    progress: 0.19,
    year: "2026",
    rating: "Livre",
  },
  {
    id: "vod-6",
    title: "Avaliação com apoio digital",
    subtitle: "Boas práticas",
    description:
      "Use recursos digitais para avaliação contínua e acompanhamento do aluno.",
    duration: "10 min",
    category: "Recomendados",
    type: "VOD",
    url: `${STREAM_BASE}/ondemand/speedcast/speedcast-demo.mp4`,
    artworkColor: "#0369a1",
    teacher: "Prof. Ana Paula",
    lessons: 5,
    progress: 0,
    year: "2026",
    rating: "Livre",
  },
  {
    id: "live-1001",
    title: "Canal 1001",
    subtitle: "Ao vivo",
    description:
      "Transmissão ao vivo de testes com HLS no ambiente do projeto.",
    duration: "AO VIVO",
    category: "Ao vivo",
    badge: "AO VIVO",
    type: "LIVE",
    url: `${STREAM_BASE}/hls/live/1001/index.m3u8`,
    artworkColor: "#991b1b",
    teacher: "Transmissão",
    lessons: 1,
    progress: 0,
    year: "Live",
    rating: "Livre",
  },
  {
    id: "live-1003",
    title: "Canal 1003",
    subtitle: "Ao vivo",
    description: "Canal em HLS para simular eventos e transmissões educativas.",
    duration: "AO VIVO",
    category: "Ao vivo",
    badge: "AO VIVO",
    type: "LIVE",
    url: `${STREAM_BASE}/hls/live/1003/index.m3u8`,
    artworkColor: "#7f1d1d",
    teacher: "Transmissão",
    lessons: 1,
    progress: 0,
    year: "Live",
    rating: "Livre",
  },
  {
    id: "live-1012",
    title: "Canal 1012",
    subtitle: "Ao vivo",
    description: "Canal de demonstração para conteúdos em tempo real.",
    duration: "AO VIVO",
    category: "Ao vivo",
    badge: "AO VIVO",
    type: "LIVE",
    url: `${STREAM_BASE}/hls/live/1012/index.m3u8`,
    artworkColor: "#881337",
    teacher: "Transmissão",
    lessons: 1,
    progress: 0,
    year: "Live",
    rating: "Livre",
  },
];

export function getFeaturedCatalogItem() {
  return catalogItems[0];
}

export function getAllCatalogItems() {
  return catalogItems;
}

export function getCatalogRows() {
  return [
    {
      id: "continue",
      title: "Continue assistindo",
      subtitle: "Retome exatamente de onde você parou",
      items: catalogItems.filter(
        (item) => item.category === "Continue assistindo",
      ),
    },
    {
      id: "live",
      title: "Canais ao vivo",
      subtitle: "Transmissões e testes em HLS",
      items: catalogItems.filter((item) => item.type === "LIVE"),
    },
    {
      id: "news",
      title: "Novidades",
      subtitle: "Conteúdos recém-adicionados à plataforma",
      items: catalogItems.filter((item) => item.category === "Novidades"),
    },
    {
      id: "recommended",
      title: "Recomendados para você",
      subtitle: "Conteúdos com maior aderência ao perfil do professor",
      items: catalogItems.filter((item) => item.category === "Recomendados"),
    },
  ];
}
